// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6b148pimPXNaQyjACguMymRPxkhCECuc',
    appId: '1:863347691265:android:aea333d00217240c695500',
    messagingSenderId: '863347691265',
    projectId: 'bloodbank-db389',
    storageBucket: 'bloodbank-db389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTZn_E1wzbzbMNs3uAMyXpmnTxTa_YVM',
    appId: '1:863347691265:ios:722e4b8c3c0a7845695500',
    messagingSenderId: '863347691265',
    projectId: 'bloodbank-db389',
    storageBucket: 'bloodbank-db389.appspot.com',
    iosClientId: '863347691265-8755em63004anbg7np4dr7spl7hg1h98.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbank',
  );
}
